### PR TITLE
Feature/storybook

### PR DESCRIPTION
**Pull request by nicholas-b-carter**
#67 - Added react-native-storybook....

### CODE REVIEW

**Comment by derickwarshaw** [comment]
This looks very interesting! Checking out the branch!

**Comment by nicholas-b-carter** [comment]
For sure. Yeah I was going to do the esdocs but saw that you just wired all that up

**Comment by bbohen** [comment]
@nicholas-b-carter How do you like using storybook? You think it would become part of the normal dev workflow?

**Comment by nicholas-b-carter** [comment]
@bbohen it might be useful... probably alot more helpful for ui development than anything else where you might have a larger team and we're trying to push code reuse... Well see

**Comment by nicholas-b-carter** [comment]
@bbohen I think https://github.com/SpencerCDixon/redux-cli would be really helpful on the flip side of just ui development. Can template out patterns, etc... pretty cool.

**Comment by derickwarshaw** [comment]
I'd be interested in getting this in should UI dev pick up and move to something a bit more complicated...would definitely like to use in a project but not in this one at this time.

**Pull request closed without merging**
